version: '2'
services:
    backend3-app:
        image: backend3
        external_links:
            - backend3-mongodb:mongodb
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=backend3
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    backend3-mongodb:
        extends:
            file: mongodb.yml
            service: backend3-mongodb
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
