version: '2'
services:
    backend3-mongodb:
        container_name: backend3-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/backend3/mongodb/:/data/db/
